# Generated by Django 5.1 on 2024-11-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlbaiviet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chuyenmuc',
            name='mo_ta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
